# Generated by Django 3.2.14 on 2023-02-01 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import streamselect.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('disability', models.CharField(max_length=100)),
                ('school_name_board', models.CharField(max_length=100)),
                ('mobile_num', models.CharField(max_length=12)),
                ('alt_mobile_num', models.CharField(max_length=12)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(null=True, upload_to=streamselect.models.UserImage.get_user_image_path)),
                ('user_image_ext', models.CharField(blank=True, max_length=20)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streamselect.userbasicinfo')),
            ],
        ),
    ]
