# Generated by Django 3.2.14 on 2023-02-10 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streamselect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicinfo',
            name='check_alerts',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
