# Generated by Django 3.2.14 on 2023-02-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamselect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_model', models.CharField(max_length=100)),
                ('nature', models.CharField(max_length=100)),
                ('com_skills', models.CharField(max_length=100)),
                ('development_course', models.CharField(max_length=100)),
                ('exam_attempts', models.CharField(max_length=100)),
                ('health_issues', models.CharField(max_length=100)),
                ('drugs', models.CharField(max_length=100)),
                ('school_type', models.CharField(max_length=100)),
                ('attendance', models.CharField(max_length=100)),
                ('scholarship', models.CharField(max_length=100)),
            ],
        ),
    ]
