# Generated by Django 3.2.14 on 2023-02-10 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamselect', '0002_userbasicinfo_check_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.CharField(max_length=100)),
                ('physics', models.CharField(max_length=100)),
                ('chemistry', models.CharField(max_length=100)),
                ('biology', models.CharField(max_length=100)),
                ('history', models.CharField(max_length=100)),
                ('geography', models.CharField(max_length=100)),
                ('commerce', models.CharField(max_length=100)),
                ('accounts', models.CharField(max_length=100)),
                ('statistics', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='sectionfive',
            old_name='beautician',
            new_name='annual_income',
        ),
        migrations.RenameField(
            model_name='sectionfive',
            old_name='computers',
            new_name='curricular',
        ),
        migrations.RenameField(
            model_name='sectionfive',
            old_name='environment_science',
            new_name='father_job',
        ),
        migrations.RenameField(
            model_name='sectionfive',
            old_name='home_science',
            new_name='father_qual',
        ),
        migrations.RenameField(
            model_name='sectionfive',
            old_name='library_asst',
            new_name='mother_job',
        ),
        migrations.RenameField(
            model_name='sectionfive',
            old_name='physical_edu',
            new_name='mother_qual',
        ),
        migrations.RenameField(
            model_name='sectionfive',
            old_name='political_science',
            new_name='performance_level',
        ),
        migrations.RenameField(
            model_name='sectionfive',
            old_name='secretarial_roles',
            new_name='sibling_job',
        ),
        migrations.RenameField(
            model_name='sectionfive',
            old_name='stenography',
            new_name='sibling_qual',
        ),
        migrations.RenameField(
            model_name='sectionfour',
            old_name='accounts',
            new_name='beautician',
        ),
        migrations.RenameField(
            model_name='sectionfour',
            old_name='biology',
            new_name='computers',
        ),
        migrations.RenameField(
            model_name='sectionfour',
            old_name='chemistry',
            new_name='environment_science',
        ),
        migrations.RenameField(
            model_name='sectionfour',
            old_name='commerce',
            new_name='home_science',
        ),
        migrations.RenameField(
            model_name='sectionfour',
            old_name='geography',
            new_name='library_asst',
        ),
        migrations.RenameField(
            model_name='sectionfour',
            old_name='history',
            new_name='physical_edu',
        ),
        migrations.RenameField(
            model_name='sectionfour',
            old_name='language',
            new_name='political_science',
        ),
        migrations.RenameField(
            model_name='sectionfour',
            old_name='math',
            new_name='secretarial_roles',
        ),
        migrations.RenameField(
            model_name='sectionfour',
            old_name='physics',
            new_name='stenography',
        ),
        migrations.RenameField(
            model_name='sectionfour',
            old_name='statistics',
            new_name='typewriting',
        ),
        migrations.RemoveField(
            model_name='sectionfive',
            name='typewriting',
        ),
        migrations.DeleteModel(
            name='SectionThird',
        ),
    ]
